"use strict";
const faker = require("faker");
const avatar = require("give-me-an-avatar");
const bcrypt = require("bcryptjs");
const { fake } = require("faker");
const { validationResult } = require("express-validator");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    //Initial users array with 'demo user' included
    const fakerPassword = faker.internet.password();
    const password = await bcrypt.hash("theSixPack!", 10);
    const randomPassword = await bcrypt.hash(fakerPassword, 10);
    //100 fake users
    let users = [
      {
        firstName: "Sean",
        lastName: "Morrison",
        email: "sean234@ymail.com",
        passwordHash: password,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: "Stephanie",
        lastName: "Vargas",
        email: "svargas@rocketmail.com",
        passwordHash: password,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: "demo",
        lastName: "user",
        email: "demo.user@demo.com",
        passwordHash: password,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
      {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: faker.internet.email(),
        passwordHash: randomPassword,
        profileImage: avatar.giveMeAnAvatar(),
        phoneNumber: faker.phone.phoneNumber(),
      },
    ];

    //Functionality to create more users will be added below

    return queryInterface.bulkInsert("Users", users, {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Users", null, {});
  },
};
